### ISSUE TITLE
Extensions array should include possible specific version of the extesion.

### ISSUE THREAD

**Issue by GustavoFenilli** [microsoft/vscode-dev-containers#969] opened 2021-07-26 17:32 UTC
Extensions array should accept a specific version of the extesion, something on the lines of:
```
"extensions": [
    "octref.vetur:0.33.1",
  ],
```

The reason being, that every time you need to rebuild the image it will install the latest version of all extensions, and/or if another developer gets the project you would need to tell them to install a specific version of the already installed extesion.

So if any extension is broken at newer versions, you could never add it to extensions.

**Comment by Chuxel** [comment] 2021-07-26 17:49
Duplicate of https://github.com/microsoft/vscode/issues/63903 and https://github.com/microsoft/vscode-remote-release/issues/3494.  Please upvote/comment on the VS Code issue. Thanks!

**Closed by Chuxel** 2021-07-26 17:49 UTC
