### ISSUE TITLE
Persist NVM cache

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-dev-containers#879] opened 2021-06-03 12:59 UTC
Image: `mcr.microsoft.com/vscode/devcontainers/javascript-node:0.202.1-16-buster`

Calling `nvm install` in my `postCreateCommand` causes a 22 MB download of the same Node.js archive on every container rebuild.

```sh
$ nvm cache dir
/usr/local/share/nvm/.cache
```

I see you're intentionally setting `NVM_DIR=/usr/local/share/nvm`, and I'm guessing there's probably a good reason for this. Nonetheless, it'd be great if I could persist this cache, ideally even by default, allowing users who want to clear it to `nvm cache clear` themselves.

**Comment by Chuxel** [comment] 2021-06-22 23:47
@aaronadamsCA Yeah that's so that it works across users.  There's a `nvm` group and anyone in it gets access. The good news is you can actually do this by adding a volume mount into your devcontainer.json in the right spot.

```json
"mounts": ["source=nvm-cache,target=/usr/local/share/nvm/.cache,type=volume"]
```

The dockerfile may need to `su node -c 'mkdir -p /usr/local/share/nvm/.cache'` so that it has the right user privs.

The downside of always doing this is that the volume will stick around even after you delete the container and, if you don't change the volume name, would be reused across containers.  Even `docker system prune -a` won't remove it... you need to do `docker system prune -a --volumes`. That's why it's not there by default at the moment.

**Comment by PavelSosin-320** [comment] 2021-06-23 04:42
@Chuxel Ia it precisely correct? The single-node Docker engine is not really multiuser because it has a single storage root and all artifacts are created under this root, including volumes with local driver. Podman, for example, is much more clever because every user has their own persistent root under $XDG_RUNTIME_DIR. All "Podman volumes" are private and can be used as a "private cache". All bind volumes can be used as a "Shared cache" but with big precautions.

**Comment by PavelSosin-320** [comment] 2021-06-23 05:45
FYI: for convinience [Manage Podman volumes for remote users](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_volume_module.html) :)

**Comment by Chuxel** [comment] 2021-06-23 13:39
@PavelSosin-320 nvm is just installed globally. Each user gets their own home. It gives you the option to run as root or vscode as you see fit. Not really related to PodMan or Docker at all.

**Comment by PavelSosin-320** [comment] 2021-06-24 05:38
@Chuxel The Docker's issue is exactly as you describe it: the docker volumes are not "owned" by the user, they are owned by the root, the Docker engine storage root owner. Every user has to manage his volumes, including bind volumes, even if the source dir is inside the user's home. In Podman volume prune by rootless user deletes user's volumes unused by the user's containers and makes them unavailable to anybody else.

**Comment by Chuxel** [comment] 2021-06-25 22:17
@PavelSosin-320 This discussion is not about Podman vs Docker. This is off-topic. Please evangelize Podman in a different forum.

**Comment by PavelSosin-320** [comment] 2021-06-26 17:56
@Chuxel This is not about Podman vs Docker. This is about the redundancy between Podman and Dev Container features. In the case when Dev Container uses Podman as backend users will get a chance to config the same thing in 2 different places with conflicting results and doubled performance cost. It may surprise him.

**Comment by PavelSosin-320** [comment] 2021-06-27 04:56
I support the Feature request itself but the proposed solution looks problematic: today's Dokerfile spec allows to define volume mounts using VOLUME directive that ensures the existence of mount point inside the container and any configuration of components inside the container can safely reference this mount point. But mount's source depends on many things like OCI backend type, versions, volume persistence possibility, and supported features, like volume drivers ( plain plugins). If this part will be included in dev container definition it will make the definition hardly portable even between 2 Docker engines. I think that it would better to adhere to the OCI concept and separate volume persistence that is runtime option from the mount point definition that can be a part of the container image to achieve container consistency, exactly as defined today by OCI specs.

**Comment by PavelSosin-320** [comment] 2021-06-28 05:35
About implementaton: I suppose that every time when some tool that used cache it makes sense to create corresponding [Docker VOLUME documentation](https://docs.docker.com/engine/reference/builder/#volume) in the image but it is completely in the developer's hands and not in VSCode and use it following documentation. The runtime source parameter depends on what developers have in their hands especially when talking about remote engine and the correct selection of backing FS may cost handreds of percents in performance gain/lost and it is not in the VSCode hands too. The cache on WSL disk will use ext4 FS that is very good and on the Windows FS means "P9 FS" and this is very bad. The mount tool used by the engine can vary too and this is in Engine configuration. WSL 2 Kernel supports FUSE adopted by the Docker and Podman as the best choice. Ability of sharing cache between users depends on the cache implementation and if the cache is created under Home directory by the default it is not sharable by design.

**Comment by PavelSosin-320** [comment] 2021-06-28 10:24
@aaronadamsCA , maybe, if you want to add some content to the image statically, like nodejs applications, then to root your problem completely the better approach is to use buildkit [buildkit](https://github.com/moby/buildkit): it is already available to you, requires minimum changes in the projects under development and will provide expected performance gain. Anyway, everything added to the image becomes the image layer and caching of layer source is equivalent of the caching of layers.

**Closed** 2021-09-14 16:21 UTC
