### ISSUE TITLE
Unable to start terminal process: CreateProcess failed

### ISSUE THREAD

**Issue by alecsg77** [microsoft/vscode-dev-containers#329] opened 2020-05-12 06:42 UTC
- VSCode Version: 1.45.0
- ms-vscode-remote.remote-containers: 0.117.0
- Local OS Version:  Microsoft Windows Version 1909 (OS Build 18363.778) and (OS Build 18363.815)
- Name of Dev Container Definition with Issue: (all)

Steps to Reproduce:

1.  Upgrade Docker Desktop community to 2.3.0.2 (45183)
2.  Try to run one of the example containers or a local devcontainer definition

[2020-05-12T06:20:38.071Z] [PID 17088] [2 ms] Start: Check Docker is running
[2020-05-12T06:20:38.071Z] [PID 17088] [2 ms] Start: Run: docker info
[2020-05-12T06:20:38.069Z] [PID 17088] [0 ms] Start: Resolving remote
[2020-05-12T06:20:40.144Z] [PID 17088] [2075 ms] Start: Run: docker volume ls -q
[2020-05-12T06:20:40.683Z] [PID 17088] [2614 ms] Start: Run: docker volume create --label vsch.local.repository=https://github.com/Microsoft/vscode-remote-try-dotnetcore --label vsch.local.repository.unique=false vsc-remote-sample
[2020-05-12T06:20:41.229Z] [PID 17088] [3160 ms] Start: Run: docker ps -q -a --filter label=vsch.local.repository=https://github.com/Microsoft/vscode-remote-try-dotnetcore --filter label=vsch.local.repository.volume=vsc-remote-sample --filter label=vsch.local.repository.folder=vscode-remote-try-dotnetcore --filter label=vsch.quality=stable
[2020-05-12T06:20:41.742Z] [PID 17088] [3673 ms] Start: Run: docker build -f c:\Users\user0\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\scripts\volumeBootstrap.Dockerfile -t vsc-volume-bootstrap c:\Users\user0\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\scripts
[2020-05-12T06:20:41.896Z] [PID 17088] [3827 ms] Error: Unable to start terminal process: CreateProcess failed
	at new WindowsPtyAgent (c:\Users\user0\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:77:36)
	at new WindowsTerminal (c:\Users\user0\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:50:24)
	at Object.spawn (c:\Users\user0\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\index.js:28:12)
	at c:\Users\user0\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:5211
	at async Object.t.runCommand (c:\Users\user0\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:8512)
	at async c:\Users\user0\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:118726
	at async Object.D [as cloneAndBuildRepository] (c:\Users\user0\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:118585)
	at async Object.t.openDockerfileRepoDevContainer (c:\Users\user0\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:165567)

**Comment by ikappas** [comment] 2020-05-12 08:31
Same here

**Comment by Chuxel** [comment] 2020-05-12 13:31
This is a dupe of https://github.com/microsoft/vscode-remote-release/issues/2975. We're seeing a number of strange issues with Docker 2.3.0.2 even outside of remote containers. We reccomend sticking with 2.2.0.5 for now.  

See here for links: https://github.com/microsoft/vscode-remote-release/issues/2975#issuecomment-626900013

Please see  https://github.com/microsoft/vscode-remote-release/issues/2975 for more info as we have it.

**Closed by Chuxel** 2020-05-12 13:31 UTC
