### ISSUE TITLE
Java 12 container complains about Maven not being on the path

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-dev-containers#186] opened 2020-01-08 14:19 UTC
![capture](https://user-images.githubusercontent.com/1931590/71985177-4bcd9180-322a-11ea-9e5e-3e749d41ea6e.png)

**Comment by Chuxel** [comment] 2020-01-08 14:57
@testforstephen @hexiaokai My recollection here was that, because of the split in the Java ecosystem between Gradle and Maven, the Dockerfiles for the Java containers have the installation of the two commented out.

Is that still the behavior you want given @dbaeumer observation?

It seems like the README should mention how to enable one or the other at a minimum. Thoughts?

**Comment by hexiaokai** [comment] 2020-01-08 16:18
I would suggest enabling Maven as default, and mention Gradle setup in README. @testforstephen

**Comment by testforstephen** [comment] 2020-01-09 03:24
See the issue https://github.com/microsoft/vscode-dev-containers/issues/31, we had a long story to discuss whether to enable mvn or gradle executables in Dockerfile by default. 

One assumption is nowadays many users would prefer to use maven or gradle wrapper to download the right build tool, so that we decide to provide a slim Dockerfile by default. The maven extension requires your project to contain an embedded wrapper, otherwise, it will go to the local bin to search mvn executable. Add @Eskibear (the author of the maven extension), is it possible to improve the warning message?

@Chuxel Agree, we need add words in README about how to manually enable the build tools.

**Comment by Eskibear** [comment] 2020-01-09 09:41
Let me clarify the current behavior a little bit. The Maven extension depends on a maven distribution to calculate some essential information (e.g. effective-pom, plugin detailed info, etc. ), before rendering them in the explorer.

It follows below order to look for the maven executable:
* setting `maven.executable.path` if not empty.
* maven wrapper under your project root folder.
* `mvn` under the PATH env.

If none is found, the warning appears.

**Comment by Chuxel** [comment] 2020-01-14 23:05
@testforstephen Given what @Eskibear describes, it sounds like the warning would appear even if just Gradle is installed.  In that event, would it make sense to have Maven there by default and people can optionally add Gradle?

**Comment by testforstephen** [comment] 2020-01-15 02:33
> Given what @Eskibear describes, it sounds like the warning would appear even if just Gradle is installed.

This is actually not directly caused by the build tool. The root cause is you're opening a maven project, and vscode-maven is auto activated and pop the warning. If you're opening a gradle project, there is no warning. This image is named as **Java 12**, it sounds a bit weird that it contains a build tool, but not another.

In your try-java sample project, could you provide a maven project with maven wrapper? This will work better.

**Comment by akaroml** [comment] 2020-01-15 03:32
I would say it's arguable to have Maven in the image by default. There was a long discussion back in the beginning.

Can we make it on-demand? Whenever Maven runtime is needed, prompt the user to install it or pack a mvnw somewhere and run it when needed? @Eskibear what do you think?

**Comment by Eskibear** [comment] 2020-01-15 06:29
> Whenever Maven runtime is needed, prompt the user to install it

This looks good to me, e.g. in the warning box, provide an "Install" button which guide users to install a distribution of Maven locally. We can either a) redirect to official Maven Installation Guide, or b) ask some question (Maven version, installation dir) and install it for users with one click. 

> pack a mvnw somewhere and run it when needed

I give a -1 vote to it. We do have packed a mvnw inside the extension. Whenever a user wants to create a Maven project from scratch, but do not have a local Maven distribution installed, this packed mvnw will be used. But it's only a workaround for beginners. mvnw belongs to a project, and should be located in project root folder. 
It is not designed to replace a Maven distribution. The behavior is unguaranteed if we force to apply the "workaround" in general case. E.g. `mvnw` script requires a `.mvn` folder in current folder (cwd), which contains properties and jar file for the wrapper. It means you cannot execute mvnw simply with its absolute path.

**Comment by akaroml** [comment] 2020-01-16 01:17
Let me clarify why I mention `mvnw`. The goal is to have some script to install Maven on-demand. The script should be very reliable to handle different environments. `mvnw` was brought up because it has both characteristics. If `mvnw` could not serve the purpose, then we need to find something else.

Here to call out one thing. Since it's a container case, suggesting users to put Maven in the image makes more sense. This is because I consider container instances transient. When users install something in an instance, it will be gone when the instance is gone. Please also take that into consideration when popping the suggestion.

**Comment by Chuxel** [comment] 2020-03-23 22:16
One other data point here is that devcontainer.json in 1.50 now supports passing in build args.  The Dockerfile could be updated to look at a build argument to know which, if either should be installed.  The devcontainer.json could then have:

```json
"build": {
    "args": {
        "INSTALL_MAVEN": "true",
        "INSTALL_GRADLE": "false"
    }
}
```

This would allow them to pick without ever having to open up the Dockerfile.

**Comment by akaroml** [comment] 2020-06-01 03:09
> One other data point here is that devcontainer.json in 1.50 now supports passing in build args. The Dockerfile could be updated to look at a build argument to know which, if either should be installed. The devcontainer.json could then have:
> 
> ```json
> "build": {
>     "args": {
>         "INSTALL_MAVEN": "true",
>         "INSTALL_GRADLE": "false"
>     }
> }
> ```
> 
> This would allow them to pick without ever having to open up the Dockerfile.

Thanks Chuck. This looks promising.  @Eskibear could you take a look at the comments from @Chuxel?

@Chuxel I'm wondering how this would be surfaced to the users through UI (e.g. ask questions before they open the workspace in a remote container). Or it stays at the code level and users need to modify `devcontainer.json` directly.

**Comment by PavelSosin-320** [comment] 2020-06-01 05:30
Reference: [Official jdk 1.8&Maven3 image](https://hub.docker.com/r/dockette/jdk8/)

**Comment by Chuxel** [comment] 2020-07-31 03:10
#456 updates the Java definition to allow people to do [this](https://github.com/microsoft/vscode-dev-containers/issues/186#issuecomment-636589268).  So closing.

**Closed by Chuxel** 2020-07-31 03:10 UTC
Labels: java, under-discussion
