### ISSUE TITLE
Problems with dotnet-dev-image on arm64

### ISSUE THREAD

**Issue by Cyber1000** [microsoft/vscode-dev-containers#825] opened 2021-04-19 23:48 UTC
- VSCode Version: 1.55.2
- Local OS Version: Windows
- Remote OS: arm64 connected via docker-engine
- Name of Dev Container Definition with Issue: dotnet (https://github.com/microsoft/vscode-dev-containers/blob/master/containers/dotnet/.devcontainer/Dockerfile)

Steps to Reproduce:

1.Use an arm64-OS with docker (x86_64 will work well)
2. Using a .devcontainer with a dotnet environment (containing this file: https://github.com/microsoft/vscode-dev-containers/blob/master/containers/dotnet/.devcontainer/Dockerfile)
3. reopening folder with remote-containers (thus building and starting docker) results in this:
![image](https://user-images.githubusercontent.com/1142765/115315084-dfed0f00-a176-11eb-87c2-faa06063774b.png)

Things to point out:
- Maybe this issue is linked to https://github.com/microsoft/vscode-remote-release/issues/3672
-  I didn't have to change "FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm64v8" like this comment states https://github.com/microsoft/vscode-remote-release/issues/3672#issuecomment-692968396
- I just used https://github.com/microsoft/vscode-dev-containers/blob/master/containers/dotnet/.devcontainer/base.Dockerfile and changed the From to "FROM mcr.microsoft.com/dotnet/sdk:${VARIANT}"
   - so I just removed the -focal, but did not add any arm64-specific label (maybe I even didn't need to remove the -focal)
   - this works well on x86_64 and arm64

I can't quite understand why there seems to be an architecture dependant https://github.com/microsoft/vscode-dev-containers/blob/master/containers/dotnet/.devcontainer/Dockerfile, which is roled out in vscode when creating a default dotnetcore environment, when there is also a https://github.com/microsoft/vscode-dev-containers/blob/master/containers/dotnet/.devcontainer/base.Dockerfile  which works perfectly well on other architectures. 
Are there any differences? I didn't find deeper differences, at least dotnetcore-projects work with both images.
Any chances to fix this in https://github.com/microsoft/vscode-dev-containers/blob/master/containers/dotnet/.devcontainer/Dockerfile and make this multiarch?

**Comment by 2percentsilk** [comment] 2021-04-21 00:10
A few clarifications that hopefully will help!
1. The base.Dockerfile builds the image so you can totally customize it if you want to. 
2. We prebuild the image from the base.Dockerfile and then reference it in the Dockerfile to make things a bit faster and streamlined for folks using this definition.

Making the definition multi-arch would require us to also update our external feeds and build scripts to be architecture aware. You can follow along with that feature request: https://github.com/microsoft/vscode-dev-containers/issues/558

**Comment by Cyber1000** [comment] 2021-04-23 20:53
Thanks for answering, hope I get this right:
- so "mcr.microsoft.com/vscode/devcontainers/dotnet:0-${VARIANT}" in Dockerfile is actually a prebuild image created out of base.Dockerfile?
- and "mcr.microsoft.com/dotnet/sdk:${VARIANT}-focal" in base.Dockerfile is a prebuild of one of these I guess: https://hub.docker.com/_/microsoft-dotnet-sdk. So some ubuntu 20.04, which would explain the "-focal" suffix.
- and there seems to be 5.0-focal for adm64 and arm64. So this explains why base.Dockerfile works on my arm64

Thanks for pointing out the feature request! Well I attach there, would be nice to have no bigger workarounds (env-files are ok :-) ) for different architecture

**Comment by Chuxel** [comment] 2021-07-12 14:21
I'm closing this as a duplicate of #558 and #914 where you can track progress.

**Closed by Chuxel** 2021-07-12 14:21 UTC
Labels: dotnet, feature-request
