### ISSUE TITLE
Inconsistency in identifying a non-root user and auto update UID & GID for vscode user

### ISSUE THREAD

**Issue by nguyenyou** [microsoft/vscode-dev-containers#603] opened 2020-10-12 09:28 UTC
- VSCode Version: 1.50.0
- Local OS Version: Ubuntu 20.04
- Name of Dev Container Definition with Issue: Python 3 & PostgreSQL

Situation: in my company, we're using **domain users** for login Ubuntu OS. My user:
```
uid = 319xxx064 (DOMAIN\myuser)
gid = 319xxx193 (DOMAIN\mygroup)
```

### AS EXPECTED

Steps to Reproduce:

1. Select **Python 3** devcontainer -> choose Python 3.8 -> check install Node
2. Uncomment `"remoteUser": "vscode"`in `.devcontainer.json` file
3. Reopen in Container
4. `cat /etc/passwd` => the user `vscode` is successfully updated 
```
vscode:x:319xxx064:319xxx193::/home/vscode:/bin/bash
```
### NOT AS EXPECTED

Steps to Reproduce:

1. Select **Python 3 & PostgreSQL** devcontainer
2. Uncomment `"remoteUser": "vscode"`in `.devcontainer.json` file
3. Reopen in Container
4. `cat /etc/passwd` => the user `vscode` is still 1000:1000
 ```
vscode:x:1000:1000::/home/vscode:/bin/bash
```
### HELP

Is this intentional or a bug? Please someone help me to get the exact behavior like the **Python 3** devcontainer does.

**Comment by Chuxel** [comment] 2020-10-12 13:33
Thanks for raising the issue. The challenge is that the auto-UID/GID sync feature is not supported with Docker Compose right now. See https://github.com/microsoft/vscode-remote-release/issues/2228.  Closing this as a dupe of the other issue.

**Closed by Chuxel** 2020-10-12 13:33 UTC
