### ISSUE TITLE
dotnet-mssql: HTTPs support in CodeSpace with port forwarding

### ISSUE THREAD

**Issue by warrenbuckley** [microsoft/vscode-dev-containers#1149] opened 2021-11-01 20:15 UTC
## Summary
Unable to browse to a dotnet new WebApp template on HTTPs 5001 port. A 502 Bad Gateway error is shown from nginx

:warning:_I am not sure this is the correct repository to report a CodeSpace issue, so please feel free to redirect me._

## Terminal Output
```
@warrenbuckley ➜ /workspaces/CodeSpace-NetCore-HTTPS/testing (main ✗) $ dotnet run
Building...
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to https://localhost:5001 on the IPv6 loopback interface: 'Cannot assign requested address'.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Cannot assign requested address'.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /workspaces/CodeSpace-NetCore-HTTPS/testing
```
![Terminal Output Screenshot](https://user-images.githubusercontent.com/1389894/139734639-0e78269a-ce23-4c0b-8665-c4e0e551dffd.png)

## Versions

- VSCode Version: 1.61.2
- Local OS Version: Version: 10.0.19043 Build 19043
- Reproduces in:  **Codespaces**
- Name of Dev Container Definition with Issue: **dotnet-mssql** with `5.0-focal`

## Steps to Reproduce:

1. Create a new blank repository with readme
2. Open new repo in Github Codespaces
3. Add DevContainer configuration for .NET C# with MSSQL
4. Add Github CLI & Azure CLI as optional extras
5. From terminal `dotnet new webapp --name Testing`
6. `cd Testing` and then `dotnet restore`
7. `dotnet build` and `dotnet run`
8. See error/warning about missing local HTTPS certificates
```
Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
      System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
      To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
```
9. Run `dotnet dev-certs https --trust`
10. Rerun `dotnet-run`
11. Wait for notification prompt about Auto Port Forwarding for 5000 and 5001
12. Try to browse to the HTTPS url which uses port 5001
13. 502 Bad Gateway error from nginx (see screenshot)

![image](https://user-images.githubusercontent.com/1389894/139735531-900808a3-fca8-42b1-ac35-c68dc26d5f77.png)

**Comment by warrenbuckley** [comment] 2021-11-01 20:16
Any ideas @dzsquared & @Chuxel ?
Apologies if this is the wrong repo but I am unsure where to report/log issues with GitHub CodeSpaces experience, so feel free to redirect me to the right location if needed please.

**Comment by warrenbuckley** [comment] 2021-11-01 20:21
## Follow up notes
The `dotnet new webapp` template uses `app.UseHttpsRedirection();` in `Startup.cs`
With this commented out then port 5000 with the HTTP port will then load correctly, with it put back in place it will try to redirect to https://localhost:5001 which is obviously not the magic GitHub port forwarded url such as 

`https://warrenbuckley-codespace-netcore-https-9qg446pcp644-5001.githubpreview.dev`

However still browsing direct to the https on port 5001 with the following link still returns the 502 bad gateway error
https://warrenbuckley-codespace-netcore-https-9qg446pcp644-5001.githubpreview.dev

**Comment by Chuxel** [comment] 2021-11-02 00:55
@warrenbuckley This is not related to images in this repository, so I'm going to close this as a dupe of https://github.com/github/feedback/discussions/7116 which is the right place to ask the question.

I would try doing this by connecting to the Codespace using VS Code client rather than the web.  I don't believe Codespaces web port forwarding supports custom SSL certs.

**Closed by Chuxel** 2021-11-02 00:55 UTC
