### ISSUE TITLE
Could not get jekyll container to work

### ISSUE THREAD

**Issue by jongio** [microsoft/vscode-dev-containers#436] opened 2020-07-26 13:38 UTC
Version: 1.48.0-insider (user setup)
Commit: 731f9c25632dbbf01ee3a7892ad9d2791fe0260c
Date: 2020-07-24T05:57:10.466Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
**WSL2**

- Name of Dev Container Definition with Issue: jekyll

Steps to Reproduce:

1. Clone https://github.com/azure/azure-sdk
1. Ctrl+P to add Jekyll devcontainer
1. Create .vscode/tasks.json and copy from here: https://github.com/microsoft/vscode-dev-containers/blob/master/containers/jekyll/.vscode/tasks.json
1. Reopen in container
1. Run `bundle exec jekyll serve --livereload`
Get this
![image](https://user-images.githubusercontent.com/2163001/88480188-4c4d2180-cf09-11ea-9e4c-44cac533c0b2.png)
```
root@073cdf38c6ed:/workspaces/azure-sdk# bundle exec jekyll serve --livereload
Could not find concurrent-ruby-1.1.5 in any of the sources
Run `bundle install` to install missing gems
```
1. Run `bundle install`
Get this
![image](https://user-images.githubusercontent.com/2163001/88480224-8dddcc80-cf09-11ea-80d6-3fc4e2a10dd9.png)
```
An error occurred while installing nokogiri (1.10.8), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.8' --source 'https://rubygems.org/'` succeeds
before bundling.

In Gemfile:
  github-pages was resolved to 202, which depends on
    jekyll-mentions was resolved to 1.4.1, which depends on
      html-pipeline was resolved to 2.12.2, which depends on
        nokogiri
```

1. Run the command suggested in error, get this:
```
root@073cdf38c6ed:/workspaces/azure-sdk# gem install nokogiri -v '1.10.8' --source 'https://rubygems.org/'
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/nokogiri-1.10.8/ext/nokogiri
/usr/bin/ruby2.5 -r ./siteconf20200726-3813-1izj1o0.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.5
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.10.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/nokogiri-1.10.8 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.10.8/gem_make.out
```

**Comment by Chuxel** [comment] 2020-07-26 14:57
@cmendible Any thoughts here on the problems listed?

**Comment by cmendible** [comment] 2020-07-26 19:28
@jongio Just added a pull request to fix the issue. You can replace the contents of your dockerfile with the one provided.

Hope it helps!

**Comment by Chuxel** [comment] 2020-07-27 00:01
Merged!  @jongio Feel free to reopen if the issue is still happening for you.

**Closed by Chuxel** 2020-07-27 00:01 UTC

**Comment by jongio** [comment] 2020-07-27 02:04
@cmendible - I appreciate the effort. But I get the same error with the updated Dockerfile.  Were you able to run the site https://github.com/azure/azure-sdk with this .devcontainer?

**Comment by cmendible** [comment] 2020-07-27 10:25
@jongio sorry I tried with one of my own repos without issues. I'll check with the https://github.com/azure/azure-sdk and come back to you with the results.

**Comment by jongio** [comment] 2020-07-27 13:00
Can you try with Ruby 2.6? I couldn’t get ghoages to work with 2.7

**Comment by cmendible** [comment] 2020-07-27 13:04
I found the culprit: **zlib1g-dev** is missing. Can you reopen the issue while a create a new PR?

**Comment by jongio** [comment] 2020-07-27 13:13
I don’t have perms to reopen the issue. But cool!

**Comment by cmendible** [comment] 2020-07-27 13:35
@Chuxel can you please check #444

**Comment by jongio** [comment] 2020-07-27 14:34
We are closer, I'm not getting that error, but I am now getting this when I try to run

`bundle exec jekyll serve`

get this:

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Invalid US-ASCII character "\xE2" on line 5
jekyll 3.8.5 | Error:  Invalid US-ASCII character "\xE2" on line 5
```

Thoughts on why not use the jekyll container: 
https://hub.docker.com/r/jekyll/jekyll/
https://dev.to/michael/compile-a-jekyll-project-without-installing-jekyll-or-ruby-by-using-docker-4184

Or the gh-pages container:
https://github.com/Starefossen/docker-github-pages

https://www.youtube.com/watch?v=6UAf8b_2juk

Keep in mind though, that GH Codespaces doesn't support Alpine yet.

**Comment by cmendible** [comment] 2020-07-27 19:20
@jongio @Chuxel I'm sorry I've been messy with the fi. But with the changes in this PR: https://github.com/microsoft/vscode-dev-containers/pull/446 you´ll be able to run the site without issues.

**Comment by Chuxel** [comment] 2020-07-27 20:57
All these have been merged now.

**Comment by kosalanuwan** [comment] 2020-10-21 04:40
@cmendible @jongio @Chuxel [Here's what I use as jekyll devcontainer (image type).](https://github.com/kosalanuwan/devcontainers/tree/main/gh-pages) It uses `jekyll/jekyll:latest` docker image instead of what you have mentioned in the dockerfile.

I thought of sending a PR but can we have both co-exists in this repo? If so what should be the name for the one I use?
