### ISSUE TITLE
devcontainer fail to start when using docker-compose 

### ISSUE THREAD

**Issue by loynoir** [microsoft/vscode-dev-containers#1595] opened 2022-08-24 05:32 UTC
- VSCode Version: 1.59.1 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa x64
- Local OS Version: ArchLinux
- Local chip architecture: <x86, arm64, Apple Silicon>
- Reproduces in: <Codespaces | Remote - Containers | Both>
- Name of Dev Container Definition with Issue:

Steps to Reproduce:

1. `vscode > devcontainer add config > show all > from compose`
2. Reopen in container
3. Log
```
Start: Run: docker inspect --type image reproduce_devcontainer_app
Command failed: docker inspect --type image reproduce_devcontainer_app
```
4. Debug
```
$ docker image ls|grep reproduce
reproduce_devcontainer-app                                              latest         xxx   About a minute ago   570MB
```

### Expected
```
Start: Run: docker inspect --type image reproduce_devcontainer-app
```

### Actual
```
Start: Run: docker inspect --type image reproduce_devcontainer_app
```

**Comment by jkeech** [comment] 2022-08-24 15:53
Thanks for reporting! This looks like a duplicate of https://github.com/microsoft/vscode-dev-containers/issues/1567 / https://github.com/microsoft/vscode-remote-release/issues/7047

Which version of Remote - Containers are you using? It should be fixed in the latest versions: https://github.com/microsoft/vscode-remote-release/issues/7047#issuecomment-1212197426.

**Closed** 2022-11-21 23:22 UTC
