### ISSUE TITLE
E: Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is not valid yet

### ISSUE THREAD

**Issue by jwyglendowski-precisionlender** [microsoft/vscode-dev-containers#240] opened 2020-02-20 13:39 UTC
I am running the following:
* Docker Desktop on 2.2.0.3 
* VS Code Version: 1.42.1 (system setup)
    Commit: c47d83b293181d9be64f27ff093689e8e7aed054
    Date: 2020-02-11T14:45:59.656Z
    Electron: 6.1.6
    Chrome: 76.0.3809.146
    Node.js: 12.4.0
    V8: 7.6.303.31-electron.0
   OS: Windows_NT x64 10.0.18363
* ms-vscode-remote.remote-containers 0.101.1

I have tried both go and rust dev-containers and am experiencing the same issue
**"E: Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is not valid yet"**

Looks like this is not an uncommon problem based on the following [article](https://blog.sleeplessbeastie.eu/2019/11/15/how-to-deal-with-repository-is-not-valid-yet-error/).

This seems like something that should work out of the box and was hoping perhaps there is a work around. So far I have not been able to find one.

**Comment by Chuxel** [comment] 2020-02-20 16:23
@jwyglendowski-precisionlender Sorry your seeing this! Unfortunately, this appears to be an issue with Docker for Windows itself with the new 2.2.0.x release tied to putting your machine to sleep.  You can track progress and comment at https://github.com/docker/for-win/issues/5593

Closing this as a duplicate of the upstream issue.

**Closed by Chuxel** 2020-02-20 16:23 UTC
Labels: duplicate, upstream

**Comment by jwyglendowski-precisionlender** [comment] 2020-02-20 18:42
Thanks for letting me know. Restarting Docker works around the problem until it's permanently fixed.
