### ISSUE TITLE
shutdownAction in devcontainer.json does not work as expected

### ISSUE THREAD

**Issue by ryu-sato** [microsoft/vscode-dev-containers#950] opened 2021-07-18 16:29 UTC
- VSCode Version: 1.58.2 (user setup), and also 1.59.0-insider (user setup)
- Local OS Version: Windows_NT x64 10.0.19043
- Name of Dev Container Definition with Issue: shutdownAction

## Steps to Reproduce:

1. Do not set "shutdownAction" in "devcontainer.json" or set it to "stopContainer".
2. Run "Open foler in container..." in VSCode
3. Run "Close remote Connection" in VSCode

## What happens

The container will not stop.

## What is the expected result

The container will stop.

**Comment by AmitRDesai** [comment] 2021-07-19 14:29
I have also had the same issue.
VSCode Version: 1.58.2
Local OS Version: Windows 10 21H1

**Comment by Chuxel** [comment] 2021-07-22 22:34
I think this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/5362 which should now be fixed in a recently released update.  Please open an issue in the https://github.com/microsoft/vscode-remote-release repository if you are still seeing problems.

**Closed by Chuxel** 2021-07-22 22:34 UTC

**Comment by ryu-sato** [comment] 2021-07-23 10:44
@Chuxel 
Thanks for the information.
Updating to VS Code 1.58 with Remote-Containers 0.187.1 solved the problem.

I'm sorry for registering an issue with vscode-dev-containers that had no root cause.
