### ISSUE TITLE
Ubuntu container: Commands take 10 seconds to return control to bash

### ISSUE THREAD

**Issue by Rappel87** [microsoft/vscode-dev-containers#986] opened 2021-08-13 08:49 UTC
- VSCode Version: 1.58.2
- Local OS Version: MacOS 11.5.1
- Name of Dev Container Definition with Issue: Ubuntu focal from https://github.com/microsoft/vscode-dev-containers/blob/main/containers/ubuntu/.devcontainer/base.Dockerfile

Steps to Reproduce:

1. Create a dev container for my Git project purely based on the Dockerfile above
2. Start devcontainer and type a command like `ls` in the containers terminal and the command takes 10 seconds to return control back to the terminal. This seems to be related to #867. On MacOS, the issue seems to arise from the git index. If I run `git status`, the problems disappears. On Windows, `git status` does not seem to help. 
I had a look at `__bash_prompt()` and could identify `if git ls-files --error-unmatch -m --directory --no-empty-directory -o --exclude-standard ":/*"` as root cause. I deactivated the `__bash_prompt()` and did some measurements:
```bash
vscode@87a39af14ba2:/workspaces/WLM$ time git ls-files --error-unmatch -m --directory --no-empty-directory -o --exclude-standard ":/*"
find_dup.perl
.devcontainer/devcontainer.json

real    0m10.230s
user    0m3.704s
sys     0m0.859s
vscode@87a39af14ba2:/workspaces/WLM$ time git status
Refresh index: 100% (11513/11513), done.
[...] (removed)

real    0m11.370s
user    0m3.925s
sys     0m0.948s
vscode@87a39af14ba2:/workspaces/WLM$ time git ls-files --error-unmatch -m --directory --no-empty-directory -o --exclude-standard ":/*"
find_dup.perl
.devcontainer/devcontainer.json

real    0m0.088s
user    0m0.012s
sys     0m0.035s

**Comment by Chuxel** [comment] 2021-08-13 14:48
@Rappel87 Are you using GitHub Codespaces or Remote - Containers?

//cc: @joshspicer @jkeech

**Comment by Rappel87** [comment] 2021-08-14 09:55
@Chuxel I am using the Remote - Containers VSCode extension.

**Comment by janitorr** [comment] 2021-08-18 13:30
Oops,. I think I might have just created a [dublicate](https://github.com/microsoft/vscode-dev-containers/issues/999) for this issue.

Anyhow, it seems to be caused by a large amount of branches in our repository (400+), just removing the branchName part from the prompt helped us, but it´s very manual step you need to do on every container using our repo so better alternative would be nice.

#999

**Comment by joshspicer** [comment] 2021-08-18 14:23
Hm, I wonder what the best solution for this is.  I doubt there's a more efficient way for us to do that initial git command, so maybe we could offer an option a way to turn off the git prompt (although that seems like an option most people would _not_ do_) 🤔

**Comment by Chuxel** [comment] 2021-08-18 15:05
@joshspicer I think we can move to an asynchronous update model: https://www.anishathalye.com/2015/02/07/an-asynchronous-shell-prompt/

**Comment by Chuxel** [comment] 2021-08-30 23:32
Merged #999 here, there are a number of scenarios that can cause this including apparently a large number of branches.

**Comment by NGPixel** [comment] 2021-11-05 23:04
Also having this issue although I only have 4 branches, so too many branches is not the problem in my case. A way to disable the gitbranch part would be great.

**Comment by Chuxel** [comment] 2021-11-09 00:14
The other place this can happen is if you're on slow disk, a network mount, or using a slower implementation of filesystem sharing than Docker Desktop provides (e.g. lima is much slower from what I've seen). Supporting the ability to disable makes sense given all of this.

**Comment by Chuxel** [comment] 2021-11-11 01:50
Opened PR #1161 that is modeled after how Oh My Zsh handles this. Once merged, you add a git setting to vary by repo (which would survive a rebuild and doesn't require a rebuild to change):

```
git config codespaces-theme.hide-status 1
```

It can also be set globally using dotfiles or a Dockerfile or postCreateCommand:

```
git config --global codespaces-theme.hide-status 1
```

**Closed** 2021-11-11 15:00 UTC
