### ISSUE TITLE
Vscode dev containers extension seems not to respect http.proxy setting

### ISSUE THREAD

**Issue by hilaolu** [microsoft/vscode-dev-containers#1703] opened 2022-12-12 07:37 UTC
Hi, I am using vscode and vscode dev containers extension with a proxy. However the extension seems to not respect http.proxy and connect to microsoft server directly, whereby vscode stuck at 'Adding dev container configure file'.

- VSCode Version:  1.74.0
- Local OS Version: Debian Buster 
- Local chip architecture: arm64
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: Debian

Steps to Reproduce:

1.  Let the local machine access Internet only via http.proxy.
2.  Open an empty folder in vscode
3.  Add dev container configure file
4.  vscode sucks

It seems that the extension tries to connect microsoft server directly.
```
netstat -an | grep 443
tcp        0      1 10.250.43.7:33536       20.189.173.14:443       SYN_SENT
```

**Comment by eitsupi** [comment] 2022-12-12 10:23
I think this is duplicate of microsoft/vscode-remote-release#7431

**Closed as completed** 2022-12-12 17:23 UTC
