### ISSUE TITLE
Docker-in-Docker will not run on Arch Linux

### ISSUE THREAD

**Issue by chand1012** [microsoft/vscode-dev-containers#1054] opened 2021-09-16 16:58 UTC
- VSCode Version: 1.60.1
- Local OS Version: Arch Linux 5.14.3-arch1-1 
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: [docker-in-docker](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/docker-in-docker)

Steps to Reproduce:

1. Add Docker-In-Docker to my project folder.
2. Try to build.
3. Error occurs.

Here are the error logs: 

[remoteContainers-2021-09-16T16-37-36.426Z.log](https://github.com/microsoft/vscode-dev-containers/files/7179605/remoteContainers-2021-09-16T16-37-36.426Z.log)

If you don't want to download the whole file, here is the TLDR.

```
[2021-09-16T16:38:33.040Z] Successfully tagged vsc-docker-in-docker-aa9a17e5628131c02e477dab975f06dd-uid:latest
[2021-09-16T16:38:33.041Z] Stop (7978 ms): Run: docker build -f /tmp/vsch/updateUID.Dockerfile-0.194.0 -t vsc-docker-in-docker-aa9a17e5628131c02e477dab975f06dd-uid --build-arg BASE_IMAGE=vsc-docker-in-docker-aa9a17e5628131c02e477dab975f06dd --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /tmp/vsch
[2021-09-16T16:38:33.042Z] Start: Run: docker -v
[2021-09-16T16:38:33.058Z] Stop (16 ms): Run: docker -v
[2021-09-16T16:38:33.058Z] Start: Run: docker events --format {{json .}} --filter event=start
[2021-09-16T16:38:33.061Z] Start: Starting container
[2021-09-16T16:38:33.061Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/chandler/Documents/personal/vscode-dev-containers,target=/workspaces/vscode-dev-containers --mount source=dind-var-lib-docker,target=/var/lib/docker,type=volume --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=/home/chandler/Documents/personal/vscode-dev-containers/containers/docker-in-docker -l vsch.quality=stable -l vsch.remote.devPort=0 --init --privileged vsc-docker-in-docker-aa9a17e5628131c02e477dab975f06dd-uid
[2021-09-16T16:38:33.306Z] Stop (245 ms): Starting container
[2021-09-16T16:38:33.307Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/chandler/Documents/personal/vscode-dev-containers/containers/docker-in-docker --filter label=vsch.quality=stable
[2021-09-16T16:38:33.309Z] Stop (251 ms): Run: docker events --format {{json .}} --filter event=start
[2021-09-16T16:38:33.312Z] sed: couldn't flush stdout: Device or resource busy
[2021-09-16T16:38:33.326Z] Stop (19 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/home/chandler/Documents/personal/vscode-dev-containers/containers/docker-in-docker --filter label=vsch.quality=stable
[2021-09-16T16:38:33.326Z] Start: Run: docker inspect --type container 6061a94e0bae
[2021-09-16T16:38:33.484Z] Stop (423 ms): Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/chandler/Documents/personal/vscode-dev-containers,target=/workspaces/vscode-dev-containers --mount source=dind-var-lib-docker,target=/var/lib/docker,type=volume --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=/home/chandler/Documents/personal/vscode-dev-containers/containers/docker-in-docker -l vsch.quality=stable -l vsch.remote.devPort=0 --init --privileged vsc-docker-in-docker-aa9a17e5628131c02e477dab975f06dd-uid
[2021-09-16T16:38:33.484Z] Stop (158 ms): Run: docker inspect --type container 6061a94e0bae
[2021-09-16T16:38:33.485Z] Start: Inspecting container
[2021-09-16T16:38:33.485Z] Start: Run: docker inspect --type container 6061a94e0baeedffa1e549b1b3057aee9361f756adb44a85e2128aee9261265e
[2021-09-16T16:38:33.503Z] Stop (18 ms): Run: docker inspect --type container 6061a94e0baeedffa1e549b1b3057aee9361f756adb44a85e2128aee9261265e
[2021-09-16T16:38:33.503Z] Stop (18 ms): Inspecting container
[2021-09-16T16:38:33.504Z] Start: Run in container: /bin/sh
[2021-09-16T16:38:33.506Z] Start: Run in container: uname -m
[2021-09-16T16:38:33.522Z] Stop (18 ms): Run in container: /bin/sh
[2021-09-16T16:38:33.522Z] Start: Run in container: cat /etc/passwd
[2021-09-16T16:38:33.522Z] Stdin closed!
[2021-09-16T16:38:33.523Z] Shell server terminated (code: 1, signal: null)

Error response from daemon: Container 6061a94e0baeedffa1e549b1b3057aee9361f756adb44a85e2128aee9261265e is not running

```

Basically the container builds successfully but will not start. I did not modify the config in any way, as I wanted to make sure I could get the plain version working before I tried to modify it.

Here is my `docker version` output.
```
Client:
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d28e
 Built:             Wed Aug  4 10:59:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d88bc
  Built:            Wed Aug  4 10:58:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.5
  GitCommit:        72cec4be58a9eb6b2910f5d10f1c01ca47d231c0.m
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Chuxel** [comment] 2021-09-16 17:11
@chand1012 I can't speak to Arch, but GitHub Codespaces runs on Ubuntu VMs where this works, so I know the issue is not with general Linux support.

See if the standard docker provided docker-in-docker image works in your setup: https://hub.docker.com/_/docker

**Comment by Chuxel** [comment] 2021-09-16 17:19
One other troubleshooting step you can take is to comment out the ENTRYPOINT line in the Dockerfile and then run `dockerd` in a terminal once you've connected to see what errors you see.  I suspect you'll see permission errors.

**Comment by chand1012** [comment] 2021-09-16 19:07
I commented out the line that starts `dockerd`, rebuilt, and got the same error. 

https://github.com/microsoft/vscode-dev-containers/blob/c98c0bc120af58933f8d168cc604fddf1499fab9/containers/docker-in-docker/.devcontainer/library-scripts/docker-in-docker-debian.sh#L227

The official nested docker image isn't going to be the best for my (and my team's) development environment since the tools we use aren't supported in Alpine Linux. I did try to get it running but couldn't as there were permission errors (even though I was root in the container). 

```
WARN[2021-09-16T19:00:19.399445306Z] Running iptables --wait -t nat -L -n failed with message: `iptables v1.8.7 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.`, error: exit status 3 
WARN[2021-09-16T19:00:19.399483841Z] Failed to find ip6tables: exec: "ip6tables": executable file not found in $PATH 
INFO[2021-09-16T19:00:19.404400393Z] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
INFO[2021-09-16T19:00:19.404539980Z] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2021-09-16T19:00:19.404543510Z] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
WARN[2021-09-16T19:00:20.405301576Z] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.7 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)
```

**Comment by chand1012** [comment] 2021-09-16 19:23
I tried to run the [`codespaces-linux`](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/codespaces-linux) image as well and again got the same error that I initially posted. I'm 90% sure that my Docker is running as root but how can I check to be sure? There's no mention of a user in the systemd unit file.

**Comment by Chuxel** [comment] 2021-09-16 23:02
Yeah the `docker` image was just to verify it still fails. That tells you it's a config problem rather than an issue with this script.

If you've alredy downloaded the huge codespaces image, run:

`docker run -it --rm --init --privileged mcr.microsoft.com/vscode/devcontainers/universal bash`

and see if it outputs any errors - like complaining about access. 

This likely is the real error:

```
 Running iptables --wait -t nat -L -n failed with message: `iptables v1.8.7 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.`, error: exit status 3 
```

One place I've seen those kinds errors is if you're using a x86 image on emulated on arm64 (or vice versea). It can also happen if iptables isn't in the kernel, Arch seems to have it in it by default: https://wiki.archlinux.org/title/Iptables   

You could also see it if you're not specifying `--init` and `--privileged` from the command line, but the docker-in-docker definition does that.

You'd only be rootless if you set it up that way (using  docker-rootless-extras-bin as explained here https://wiki.archlinux.org/title/Docker)

Arch is highly flexible - so it's a bit hard to know what is going on.

**Comment by chand1012** [comment] 2021-09-17 13:57
This is the output of the above command.
```
[chandler@Desktop-Arch ~]$ docker run -it --rm --init --privileged mcr.microsoft.com/vscode/devcontainers/universal bash
Unable to find image 'mcr.microsoft.com/vscode/devcontainers/universal:latest' locally
latest: Pulling from vscode/devcontainers/universal
Digest: sha256:b749ad2fdcaa78c4958a053af36f423194a640facbebc5b3250eb3c0eaaf5b1f
Status: Downloaded newer image for mcr.microsoft.com/vscode/devcontainers/universal:latest
/usr/local/share/docker-init.sh: line 45: /sys/fs/cgroup/init/cgroup.procs: Permission denied
```
I did double check to make sure I have the correct iptables version, and I have the same one that some of the other containers had. 
```
[chandler@Desktop-Arch ~]$ iptables --version
iptables v1.8.7 (legacy)
```

And I did install the recommended Docker Arch Linux package when I got Docker up and running (not rootless).

**Comment by hihanley** [comment] 2021-11-11 17:45
I have same problem in fedora 35.

**Comment by hihanley** [comment] 2021-11-11 18:04
image: mcr.microsoft.com/vscode/devcontainers/universal:1-focal
vscode log: container stopped, Error response from daemon
container log: /usr/local/share/docker-init.sh: line 45: /sys/fs/cgroup/init/cgroup.procs: Permission denied

**Comment by Chuxel** [comment] 2021-11-11 22:19
@chand1012 I may have stumbled upon a possible cause. There is an updated version of the docker-in-docker script that may fix this problem. Grab the latest docker-in-docker script to see if that works for you.

@hihanley Try the current development version of the codespaces image to see if it resolves your problem: `mcr.microsoft.com/vscode/devcontainers/universal:dev-focal`

//cc: @chrmarti @joshspicer as FYI

/cc: @joshspicer

**Comment by mianowski** [comment] 2021-11-12 09:45
Hi, I've got the same problem as I upgraded to Ubuntu 21.10 (on 21.04 I had docker installed with snap)

**Comment by hihanley** [comment] 2021-11-12 09:56
@Chuxel Thanks! `mcr.microsoft.com/vscode/devcontainers/universal:dev-focal` is worked.

**Comment by mianowski** [comment] 2021-11-12 10:06
@Chuxel I just copied the newest code from https://github.com/microsoft/vscode-dev-containers/blob/main/containers/docker-in-docker/.devcontainer/library-scripts and it worked for me too

**Comment by Chuxel** [comment] 2021-11-12 14:35
Great!  I'll close this as resolved and we'll get this deployed with the next update.

**Closed by Chuxel** 2021-11-12 14:35 UTC
Labels: needs-more-info

**Comment by chand1012** [comment] 2021-11-12 15:25
Worked for me as well. Thanks!
