### ISSUE TITLE
Automatically open a generated workspace file within a container

### ISSUE THREAD

**Issue by dslijepcevic** [microsoft/vscode-dev-containers#625] opened 2020-10-28 00:18 UTC
I would like this extension to automatically open a given `.code-workspace` file after the dev container gets built. The workspace file is being generated inside of the container at the end of its build process (in `postCreateCommand` to be exact). Currently this is a two step process -- "Open (Dummy) Folder in Container" followed by "Open Workspace" since the workspace file is dynamic and stored outside of `workspaceMount` and so "Open Workspace in Container" cannot be used. Could you please add a facility for making this scenario play out seamlessly, maybe something like a `workspaceFile` setting in `.devcontainer.json`? I'm not sure if there is another way of doing the same thing programatically, perhaps using an existing command or an extension that could load the workspace file in a pre-determined location inside of a container. Thanks!

**Comment by Chuxel** [comment] 2020-10-28 01:21
Thanks for the request. I think this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/3665.  Assuming so, would be great if you'd upvote (👍) the issue.

**Comment by dslijepcevic** [comment] 2020-10-28 06:45
I did upvote it, thank you for the quick response and hope :)

**Comment by Chuxel** [comment] 2020-10-28 19:03
Sounds good! Closing.

**Closed by Chuxel** 2020-10-28 19:03 UTC
