### ISSUE TITLE
[kubernetes-helm] curl docker compose URL is wrong

### ISSUE THREAD

**Issue by ijaouani** [microsoft/vscode-dev-containers#1083] opened 2021-09-30 09:33 UTC
- VSCode Version: 1.60.2
- Local OS Version: Windows 10 21H1
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: Kubernetes Helm

# Steps to Reproduce:

1. Create a project from scratch
2. Build the devcontainer
3. Following errors appear during devcontainer build :

```
7 39.09 curl: (22) The requested URL returned error: 404
executor failed running [/bin/sh -c apt-get update && /bin/bash /tmp/library-scr
ipts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}"
 "${UPGRADE_PACKAGES}" "true" "true"     && /bin/bash /tmp/library-scripts/docke
r-debian.sh "true" "/var/run/docker-host.sock" "/var/run/docker.sock" "${USERNAM
E}" "${USE_MOBY}"     && /bin/bash /tmp/library-scripts/kubectl-helm-debian.sh "
latest" "latest" "none"     && /bin/bash /tmp/library-scripts/azcli-debian.sh
  && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /t
mp/library-scripts/]: exit code: 22
```

# Diagnostics and solution to fix it:

Here https://github.com/microsoft/vscode-dev-containers/blob/main/containers/kubernetes-helm/.devcontainer/library-scripts/docker-debian.sh#L211:

The request generated is wrong :
https://github.com/docker/compose/releases/download/v2.0.0/docker-compose-Linux-x86_64

In https://github.com/docker/compose/releases repo since 2.0 "Linux-x86_64" does not exist anymore. It needs to be change to https://github.com/docker/compose/releases/download/v2.0.0/docker-compose-linux-amd64

**Comment by Chuxel** [comment] 2021-09-30 13:39
Dupe of https://github.com/microsoft/vscode-dev-containers/issues/1075.  Please update library-scripts/docker-debian.sh or library-scripts/docker-in-docker-debian.sh to the latest from the script-library folder in this repository.

**Closed by Chuxel** 2021-09-30 13:39 UTC
